service: basic-function 

provider:
  name: aws
  runtime: ruby2.5
  region: eu-west-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: post
      - http:
          path: hello
          method: get        